In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt

from pose_estimation import PoseData, PoseDataNPZ, PoseDataNPZTorch, COLOR_PALETTE

WORKDIR = f"{os.getcwd()}/.."
DATA_FOLDER = os.path.join(WORKDIR, "data_folder")
DATASET_NPZ_PATH = os.path.join(DATA_FOLDER, "dataset_npz")


In [2]:
dataset = None
dataset = PoseDataNPZ(DATASET_NPZ_PATH)


Presumed Preloaded NPZ Dataset: /Users/armanommid/Code/CSE/CSE275/HW2/XSwinDiffusion/../data_folder/dataset_npz


In [23]:
x = 0
for i, key in enumerate(dataset.keylist):
    id1 = dataset[key]["meta"][()]["object_ids"]
    id2 = dataset[key]["meta"][()]["objects"]

    if not np.array_equal(id1, id2):
        # print(type(id1), type(id2))
        # print(id1, id2)
        x += 1
print(x)


<class 'numpy.ndarray'> <class 'list'>
[ 8 14 18 29 30 35 42 48 55 57] [8, 14, 29, 30, 35, 42, 48, 55, 57]
<class 'numpy.ndarray'> <class 'list'>
[ 5  8 14 20 42 51 55 56 57 58] [8, 14, 20, 42, 51, 55, 56, 57, 58]
<class 'numpy.ndarray'> <class 'list'>
[ 8 30 35 39 42 43 50 51 57 58] [8, 30, 35, 39, 42, 43, 50, 51, 58]
<class 'numpy.ndarray'> <class 'list'>
[ 8 13 14 29 35 39 42 51 52 57] [8, 14, 29, 35, 39, 42, 51, 52, 57]
<class 'numpy.ndarray'> <class 'list'>
[ 8 14 18 29 30 35 42 48 55 57] [8, 14, 18, 29, 30, 35, 42, 48, 57]
<class 'numpy.ndarray'> <class 'list'>
[ 5  8 14 20 42 51 55 56 57 58] [5, 8, 14, 20, 42, 51, 55, 56, 58]
<class 'numpy.ndarray'> <class 'list'>
[ 8 14 20 21 30 35 39 42 55 57] [8, 14, 20, 30, 35, 39, 42, 55, 57]
<class 'numpy.ndarray'> <class 'list'>
[14 27 30 35 36 44 51 54 55 58] [14, 27, 30, 35, 44, 51, 54, 55, 58]
<class 'numpy.ndarray'> <class 'list'>
[ 8 14 20 21 30 35 39 42 55 57] [8, 20, 21, 30, 35, 39, 42, 55, 57]
<class 'numpy.ndarray'> <class 'list'