In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt

import torch
from torch.utils.data import DataLoader

from torchinfo import summary
from models import XSwinFusion 
from pose_estimation import PoseDataNPZTorch


WORKDIR = f"{os.getcwd()}/.."
DATA_FOLDER = os.path.join(WORKDIR, "data_folder")
DATASET_NPZ_PATH = os.path.join(DATA_FOLDER, "dataset_npz")


In [2]:
x = torch.tensor([0, 1, 2, 3, 4, 5])

x = x[[2,3, 2,3,2 ,3 ,2 ,3]]
x


tensor([2, 3, 2, 3, 2, 3, 2, 3])

In [3]:
samples = 10_000
resize = (432, 768)
aspect_ratio = True
margin = 12
feature_dims = 64

fusion = XSwinFusion(feature_dims=feature_dims, resize=resize)

dataset = None
dataset = PoseDataNPZTorch(DATASET_NPZ_PATH, samples=samples, 
                           resize=resize, aspect_ratio=aspect_ratio, margin=margin)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

summary(fusion)


Presumed Preloaded NPZ Dataset: /Users/armanommid/Code/CSE/CSE275/HW2/XSwinDiffusion/../data_folder/dataset_npz


In [4]:
points = []

for i, (s, t, c, d, mi, p) in enumerate(dataloader):

    print(t.shape, c.shape, d.shape)

    rgb, pcd, transforms = fusion(t, c, mi)


    if i == 3: 
        assert 0


torch.Size([2, 10000, 3]) torch.Size([2, 3, 432, 768]) torch.Size([2, 432, 768])
torch.Size([2, 1024, 1])
torch.Size([2, 1024, 10000])
torch.Size([2, 1088, 10000])
A
torch.Size([2, 64, 10000]) torch.Size([2, 64, 10000])
torch.Size([2, 64, 10000])
torch.Size([2, 128, 10000])
tensor([ 0.3554,  0.1095,  0.1000,  0.1400, -0.0024,  0.6039,  0.2666,  0.2106,
         0.2108,  0.4986,  0.0088,  0.4583,  0.3774,  0.1169,  0.5171,  0.1880,
         0.0898,  0.0686,  0.6631,  0.4967,  0.4967,  0.1584,  0.2523,  0.4538,
         0.0266,  0.3957,  0.6143,  0.4359,  0.4398,  0.2806,  0.2322,  0.3176,
         0.0169,  0.6143,  0.1059,  0.7302,  0.1821,  0.3871,  0.0276,  0.1914,
         0.2084,  0.6434,  0.3607,  0.1720,  0.1372,  0.1615,  0.0320,  0.5819,
         0.2231,  0.0658,  0.2169,  0.7417,  0.1511,  0.6115,  0.2998,  0.7235,
         0.3698,  0.0728,  0.4343,  0.3168,  0.2881,  0.4695,  0.6572,  0.2588],
       grad_fn=<SelectBackward0>)
tensor([ 0.3554,  0.1095,  0.1000,  0.1400, -0.002

ValueError: not enough values to unpack (expected 3, got 2)